# Generated by Django 4.2.5 on 2023-09-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
