# Generated by Django 4.2.5 on 2023-10-01 00:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_casemodel_image2_casemodel_image3_casemodel_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemodel',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
