# Generated by Django 4.2.5 on 2023-10-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20231001_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=15, unique=True),
        ),
    ]
