# Generated by Django 4.2.5 on 2023-10-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_casemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, unique=True),
        ),
    ]
