# Generated by Django 4.2.5 on 2023-10-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_casemodel_price_casemodel_price_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.TextField(blank=True, choices=[('2B', 'قیمت تا ۲ میلیار'), ('4B', 'قیمت ۲ تا ۴ میلیار'), ('6B', 'قیمت ۴ تا ۶ میلیار'), ('10B', 'قیمت ۶ تا ۱۰ میلیارد'), ('10B+', 'بیشتر از ۱۰ میلیارد')], null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='locationcategory',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='price_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.pricecategory'),
        ),
    ]
