# Generated by Django 4.2.5 on 2023-10-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_pricecategory_alter_locationcategory_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationcategory',
            old_name='location',
            new_name='location_title',
        ),
        migrations.AddField(
            model_name='locationcategory',
            name='location_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='price_range',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.pricecategory'),
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='price_range',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
