# Generated by Django 4.2.5 on 2023-10-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_location_locationcategory_location_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_r', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='casemodel',
            name='type_r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.typecategory'),
        ),
    ]
