# Generated by Django 4.2.5 on 2023-10-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_typecategory_casemodel_type_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='typecategory',
            name='type_r_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
