# Generated by Django 4.2.5 on 2023-10-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_locationcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
