# Generated by Django 4.2.5 on 2023-09-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_imagemodel_casemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images'),
        ),
    ]
