# Generated by Django 4.2.5 on 2023-10-01 00:19

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("pages", "CaseModel")
    for row in MyModel.objects.all():
        row.slug = uuid.uuid4()
        row.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_casemodel_slug'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
