# Generated by Django 4.2.5 on 2023-10-01 00:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20231001_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
