# Generated by Django 4.2.5 on 2023-10-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_locationcategory_pricecategory_casemodel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemodel',
            name='price',
        ),
        migrations.AddField(
            model_name='casemodel',
            name='price_range',
            field=models.TextField(blank=True, choices=[('تا ۲ میلیار', '2B'), ('', '4B'), ('', '6B'), ('', '10B'), ('', '10B+')], null=True),
        ),
        migrations.AlterField(
            model_name='locationcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='PriceCategory',
        ),
    ]
